---
  dataSource: "issues"
  prefix: "v"
  includeMessages: "commits"
  changelogFilename: "CHANGELOG.md"
  ignoreCommitsWith: ["chore", "github"]
  ignoreIssuesWith: "continues deployment"
  groupBy:
    Enhancements: ["enhancement", "feature"]
    Bug Fixes: ["bug"]
