theme: jekyll-theme-cayman
show_downloads: true
github:
  deb_url: https://github.com/xetra11/CK3-Workbench/releases/download/0.0.51/ck3-workbench_0.0.51-1_amd64.deb
  dmg_url: https://github.com/xetra11/CK3-Workbench/releases/download/0.0.51/ck3-workbench-0.0.51.dmg

